spring:
  datasource:
    url: jdbc:h2:mem:testdb;MODE=MySQL

jpa:
  open-in-view: false
  show-sql: true
  hibernate:
    ddl-auto: update
  defer-datasource-initialization: true
  properties:
    hibernate:
      format_sql: true
      use_sql_comments: true

jwt:
  secret:
    key: testtesttesttesttesttesttesttesttesttesttesttesttesttesttesttesttesttesttesttesttest